apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-nodeport-service
spec:
  ports:
  - port: 27017
    protocol: tcp
    targetPort: 27017
    nodePort: 3200
  selector:
    app: mongo
    type: NodePort
status:
  loadBalancer: {}

#kubectl create -f mongodb-nodeport.yaml

#mongo --host <ip> --port <port of nodeport svc> -u adminuser -p password123