apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeNmae: pv
  resources:
    requests:
      storage: 1GI

#check for resources before create PVC volume or try to PV storage:

#apiVersion: v1
#kind: PersistentVolume
#metadata:
  #name: mongo-pv
#spec:
  #accessModes:
   # - ReadWriteOnce
  #capacity:
   # storage: 1Gi
  #hostPath:
    #path: /data/mongo